_extends: .github

repository:
  name: website
  description: "Our organization website"
  private: false

branches:
  - name: main
    protection:
      required_status_checks:
        checks:
          - context: CodeQL
          - context: ESLint
          - context: DeepScan
          - context: Test Build
